Sprint 5
ClevertecFrontendLab/olesiklesha pull request #5
Opened 2024-03-25 15:22 UTC by olesiklesha

2024-03-25 15:24 UTC, ValadzkoAliaksei commented
#  Результаты тестов
Процент пройденных тестов: 80%.
Общее количество тестов: 5.
Количество непройденных тестов: 1.

2024-03-25 15:35 UTC, ValadzkoAliaksei commented
#  Результаты тестов
Процент пройденных тестов: 80%.
Общее количество тестов: 5.
Количество непройденных тестов: 1.

2024-03-25 17:35 UTC, ValadzkoAliaksei commented
#  Результаты тестов
Процент пройденных тестов: 80%.
Общее количество тестов: 5.
Количество непройденных тестов: 1.

2024-03-26 07:59 UTC, ValadzkoAliaksei commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 5.
Количество непройденных тестов: 0.
***
**buy-tariff-success_1440x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/olesiklesha/1711439975/buy-tariff-success_1440x900.png)
***
**default-profile-page_1440x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/olesiklesha/1711439975/default-profile-page_1440x900.png)
***
**default-settings-page_1440x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/olesiklesha/1711439975/default-settings-page_1440x900.png)
***
**feedbacks with photo_1440x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/olesiklesha/1711439975/feedbacks%20with%20photo_1440x900.png)
***
**modal-big-photo_1440x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/olesiklesha/1711439975/modal-big-photo_1440x900.png)
***
**profile-modal-error_1440x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/olesiklesha/1711439975/profile-modal-error_1440x900.png)
***
**profile-modal-success_1440x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/olesiklesha/1711439975/profile-modal-success_1440x900.png)
***
**settings-page-with-sider_360x740.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/olesiklesha/1711439975/settings-page-with-sider_360x740.png)
***
**settings-pro-cards_360x740.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/olesiklesha/1711439975/settings-pro-cards_360x740.png)
***
**settings-sider-pro_833x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/olesiklesha/1711439975/settings-sider-pro_833x900.png)

2024-03-26 08:04 UTC, SergeyGlazun approved these changes
![image](https://github.com/ClevertecFrontendLab/olesiklesha/assets/70904466/6b7d189a-8444-41f0-a016-3019165a93a3)
тут сверь с фигмой чутка отступов должно быть по больше

2024-03-26 09:50 UTC, vvikota requested changes

2024-03-26 09:50 UTC, vvikota commented on src/components/profile-form/profile-form.css
> +        /* display: flex; */
удалить комменты

2024-03-26 09:50 UTC, vvikota commented on src/components/profile-form/profile-form.tsx
> +            const imageSrc = `https://training-api.clevertec.ru/${res.data.url}`;
https://training-api.clevertec.ru в константу

2024-03-26 09:50 UTC, vvikota commented on src/components/profile-form/profile-form.tsx
> +    const handleRequest = async (options: UploadRequestOption) => {
тут у тебя логика запроса, такое лучше вынести из компонента в отдельный файл

2024-03-26 09:50 UTC, vvikota commented on src/components/profile-form/profile-form.tsx
> +                                    format='DD.MM.YYYY'
формат даты в константу

2024-03-26 09:50 UTC, vvikota commented on src/components/results/registration-error/registration-error.tsx
>      const handleClick = () => {
const handleClick = () => history.push(Paths.REGISTRATION);

2024-03-26 09:50 UTC, vvikota commented on src/components/settings-features-form/settings-features-form.tsx
> +    const onTrainingChange = (value: boolean) => {
не нужны фигурные скобки

2024-03-26 09:50 UTC, vvikota commented on src/components/settings-header/settings-header.css
> +        font-weight: 400;
жирность шрифта также можно в константу выносить

2024-03-26 10:49 UTC, ValadzkoAliaksei commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 5.
Количество непройденных тестов: 0.
***
**buy-tariff-success_1440x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/olesiklesha/1711450178/buy-tariff-success_1440x900.png)
***
**default-profile-page_1440x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/olesiklesha/1711450178/default-profile-page_1440x900.png)
***
**default-settings-page_1440x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/olesiklesha/1711450178/default-settings-page_1440x900.png)
***
**feedbacks with photo_1440x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/olesiklesha/1711450178/feedbacks%20with%20photo_1440x900.png)
***
**modal-big-photo_1440x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/olesiklesha/1711450178/modal-big-photo_1440x900.png)
***
**profile-modal-error_1440x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/olesiklesha/1711450178/profile-modal-error_1440x900.png)
***
**profile-modal-success_1440x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/olesiklesha/1711450178/profile-modal-success_1440x900.png)
***
**settings-page-with-sider_360x740.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/olesiklesha/1711450178/settings-page-with-sider_360x740.png)
***
**settings-pro-cards_360x740.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/olesiklesha/1711450178/settings-pro-cards_360x740.png)
***
**settings-sider-pro_833x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/olesiklesha/1711450178/settings-sider-pro_833x900.png)

2024-03-26 15:52 UTC, merged